repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.1
  hooks:
    - id: ruff
      args: [--fix]
      stages: [pre-commit]
    - id: ruff-format
      stages: [pre-commit]
- repo: local
  hooks:
    - id: mypy
      name: mypy
      language: system
      entry: python -m mypy
      types: [python]
      stages: [pre-commit]
      require_serial: true

