version: '2'

services:
  postgres:
    image: postgres:11.5
    command: -c fsync=off -c full_page_writes=off -c shared_buffers=512MB -c autovacuum=off
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"